name: Elixir CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Update apt
      run: sudo apt-get update
    - name: Install ImageMagick
      run: sudo apt install imagemagick
    - name: Install Ffmpeg
      run: sudo apt install ffmpeg
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: MEDIA_TEST=test mix test
    - name: Run Credo
      run: mix credo --strict
